./run2.sh avrora avrora
./run2.sh avrora batik
./run2.sh avrora h2
./run2.sh avrora jython
./run2.sh avrora lusearch
./run2.sh avrora sunflow
./run2.sh avrora tradebeans
./run2.sh avrora tradesoap
./run2.sh avrora xalan
./run2.sh batik avrora
./run2.sh batik batik
./run2.sh batik h2
./run2.sh batik jython
./run2.sh batik lusearch
./run2.sh batik sunflow
./run2.sh batik tradebeans
./run2.sh batik tradesoap
./run2.sh batik xalan
./run2.sh h2 avrora
./run2.sh h2 batik
./run2.sh h2 h2
./run2.sh h2 jython
./run2.sh h2 lusearch
./run2.sh h2 sunflow
./run2.sh h2 tradebeans
./run2.sh h2 tradesoap
./run2.sh h2 xalan
./run2.sh jython avrora
./run2.sh jython batik
./run2.sh jython h2
./run2.sh jython jython
./run2.sh jython lusearch
./run2.sh jython sunflow
./run2.sh jython tradebeans
./run2.sh jython tradesoap
./run2.sh jython xalan
./run2.sh lusearch avrora
./run2.sh lusearch batik
./run2.sh lusearch h2
./run2.sh lusearch jython
./run2.sh lusearch lusearch
./run2.sh lusearch sunflow
./run2.sh lusearch tradebeans
./run2.sh lusearch tradesoap
./run2.sh lusearch xalan
./run2.sh sunflow avrora
./run2.sh sunflow batik
./run2.sh sunflow h2
./run2.sh sunflow jython
./run2.sh sunflow lusearch
./run2.sh sunflow sunflow
./run2.sh sunflow tradebeans
./run2.sh sunflow tradesoap
./run2.sh sunflow xalan
./run2.sh tradebeans avrora
./run2.sh tradebeans batik
./run2.sh tradebeans h2
./run2.sh tradebeans jython
./run2.sh tradebeans lusearch
./run2.sh tradebeans sunflow
./run2.sh tradebeans tradebeans
./run2.sh tradebeans tradesoap
./run2.sh tradebeans xalan
./run2.sh tradesoap avrora
./run2.sh tradesoap batik
./run2.sh tradesoap h2
./run2.sh tradesoap jython
./run2.sh tradesoap lusearch
./run2.sh tradesoap sunflow
./run2.sh tradesoap tradebeans
./run2.sh tradesoap tradesoap
./run2.sh tradesoap xalan
./run2.sh xalan avrora
./run2.sh xalan batik
./run2.sh xalan h2
./run2.sh xalan jython
./run2.sh xalan lusearch
./run2.sh xalan sunflow
./run2.sh xalan tradebeans
./run2.sh xalan tradesoap
./run2.sh xalan xalan
