run4.sh  xalan xalan xalan xalan
run4.sh  sunflow xalan xalan xalan
run4.sh  sunflow sunflow xalan xalan
run4.sh  sunflow sunflow sunflow xalan
run4.sh  sunflow sunflow sunflow sunflow
run4.sh  lusearch xalan xalan xalan
run4.sh  lusearch sunflow xalan xalan
run4.sh  lusearch sunflow sunflow xalan
run4.sh  lusearch sunflow sunflow sunflow
run4.sh  lusearch lusearch xalan xalan
run4.sh  lusearch lusearch sunflow xalan
run4.sh  lusearch lusearch sunflow sunflow
run4.sh  lusearch lusearch lusearch xalan
run4.sh  lusearch lusearch lusearch sunflow
run4.sh  lusearch lusearch lusearch lusearch
run4.sh  luindex xalan xalan xalan
run4.sh  luindex sunflow xalan xalan
run4.sh  luindex sunflow sunflow xalan
run4.sh  luindex sunflow sunflow sunflow
run4.sh  luindex lusearch xalan xalan
run4.sh  luindex lusearch sunflow xalan
run4.sh  luindex lusearch sunflow sunflow
run4.sh  luindex lusearch lusearch xalan
run4.sh  luindex lusearch lusearch sunflow
run4.sh  luindex lusearch lusearch lusearch
run4.sh  luindex luindex xalan xalan
run4.sh  luindex luindex sunflow xalan
run4.sh  luindex luindex sunflow sunflow
run4.sh  luindex luindex lusearch xalan
run4.sh  luindex luindex lusearch sunflow
run4.sh  luindex luindex lusearch lusearch
run4.sh  luindex luindex luindex xalan
run4.sh  luindex luindex luindex sunflow
run4.sh  luindex luindex luindex lusearch
run4.sh  luindex luindex luindex luindex
run4.sh  jython xalan xalan xalan
run4.sh  jython sunflow xalan xalan
run4.sh  jython sunflow sunflow xalan
run4.sh  jython sunflow sunflow sunflow
run4.sh  jython lusearch xalan xalan
run4.sh  jython lusearch sunflow xalan
run4.sh  jython lusearch sunflow sunflow
run4.sh  jython lusearch lusearch xalan
run4.sh  jython lusearch lusearch sunflow
run4.sh  jython lusearch lusearch lusearch
run4.sh  jython luindex xalan xalan
run4.sh  jython luindex sunflow xalan
run4.sh  jython luindex sunflow sunflow
run4.sh  jython luindex lusearch xalan
run4.sh  jython luindex lusearch sunflow
run4.sh  jython luindex lusearch lusearch
run4.sh  jython luindex luindex xalan
run4.sh  jython luindex luindex sunflow
run4.sh  jython luindex luindex lusearch
run4.sh  jython luindex luindex luindex
run4.sh  jython jython xalan xalan
run4.sh  jython jython sunflow xalan
run4.sh  jython jython sunflow sunflow
run4.sh  jython jython lusearch xalan
run4.sh  jython jython lusearch sunflow
run4.sh  jython jython lusearch lusearch
run4.sh  jython jython luindex xalan
run4.sh  jython jython luindex sunflow
run4.sh  jython jython luindex lusearch
run4.sh  jython jython luindex luindex
run4.sh  jython jython jython xalan
run4.sh  jython jython jython sunflow
run4.sh  jython jython jython lusearch
run4.sh  jython jython jython luindex
run4.sh  jython jython jython jython
run4.sh  batik xalan xalan xalan
run4.sh  batik sunflow xalan xalan
run4.sh  batik sunflow sunflow xalan
run4.sh  batik sunflow sunflow sunflow
run4.sh  batik lusearch xalan xalan
run4.sh  batik lusearch sunflow xalan
run4.sh  batik lusearch sunflow sunflow
run4.sh  batik lusearch lusearch xalan
run4.sh  batik lusearch lusearch sunflow
run4.sh  batik lusearch lusearch lusearch
run4.sh  batik luindex xalan xalan
run4.sh  batik luindex sunflow xalan
run4.sh  batik luindex sunflow sunflow
run4.sh  batik luindex lusearch xalan
run4.sh  batik luindex lusearch sunflow
run4.sh  batik luindex lusearch lusearch
run4.sh  batik luindex luindex xalan
run4.sh  batik luindex luindex sunflow
run4.sh  batik luindex luindex lusearch
run4.sh  batik luindex luindex luindex
run4.sh  batik jython xalan xalan
run4.sh  batik jython sunflow xalan
run4.sh  batik jython sunflow sunflow
run4.sh  batik jython lusearch xalan
run4.sh  batik jython lusearch sunflow
run4.sh  batik jython lusearch lusearch
run4.sh  batik jython luindex xalan
run4.sh  batik jython luindex sunflow
run4.sh  batik jython luindex lusearch
run4.sh  batik jython luindex luindex
run4.sh  batik jython jython xalan
run4.sh  batik jython jython sunflow
run4.sh  batik jython jython lusearch
run4.sh  batik jython jython luindex
run4.sh  batik jython jython jython
run4.sh  batik batik xalan xalan
run4.sh  batik batik sunflow xalan
run4.sh  batik batik sunflow sunflow
run4.sh  batik batik lusearch xalan
run4.sh  batik batik lusearch sunflow
run4.sh  batik batik lusearch lusearch
run4.sh  batik batik luindex xalan
run4.sh  batik batik luindex sunflow
run4.sh  batik batik luindex lusearch
run4.sh  batik batik luindex luindex
run4.sh  batik batik jython xalan
run4.sh  batik batik jython sunflow
run4.sh  batik batik jython lusearch
run4.sh  batik batik jython luindex
run4.sh  batik batik jython jython
run4.sh  batik batik batik xalan
run4.sh  batik batik batik sunflow
run4.sh  batik batik batik lusearch
run4.sh  batik batik batik luindex
run4.sh  batik batik batik jython
run4.sh  batik batik batik batik
